# Generated by Django 4.2.26 on 2025-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description_id', models.TextField(blank=True, verbose_name='Deskripsi (ID)')),
                ('description_en', models.TextField(blank=True, verbose_name='Deskripsi (EN)')),
                ('start_date', models.DateField(help_text='Digunakan untuk pengurutan data')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_id', models.CharField(max_length=200, verbose_name='Judul Project (ID)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Judul Project (EN)')),
                ('desc_id', models.TextField(verbose_name='Deskripsi (ID)')),
                ('desc_en', models.TextField(verbose_name='Deskripsi (EN)')),
                ('tech_stack', models.CharField(help_text='Contoh: Python, Django, React', max_length=255)),
                ('image', models.URLField(blank=True, help_text='URL Gambar Project', max_length=500, null=True)),
                ('video', models.URLField(blank=True, help_text='URL Video Demo (Youtube/Lainnya)', max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0, help_text='Angka lebih kecil tampil lebih dulu')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(help_text="Isi 'True' atau 'False' jika ini adalah boolean toggle")),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Kunci unik untuk pemanggilan di template', max_length=255, unique=True)),
                ('val_id', models.TextField(verbose_name='Nilai (Indonesia)')),
                ('val_en', models.TextField(verbose_name='Nilai (Inggris)')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(max_length=200, verbose_name='Posisi (ID)')),
                ('role_en', models.CharField(max_length=200, verbose_name='Posisi (EN)')),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(help_text='Contoh: Jan 2023 - Present', max_length=100)),
                ('responsibilities_id', models.TextField(help_text='Pisahkan setiap poin dengan baris baru (Enter)', verbose_name='Tanggung Jawab (ID)')),
                ('responsibilities_en', models.TextField(help_text='Pisahkan setiap poin dengan baris baru (Enter)', verbose_name='Tanggung Jawab (EN)')),
                ('start_date', models.DateField(help_text='Digunakan untuk pengurutan data secara kronologis')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
