# Generated by Django 4.2.26 on 2025-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('major_id', models.CharField(max_length=200)),
                ('major_en', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description_id', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('tools', 'Tools'), ('nontech', 'Non-Technical'), ('lang', 'Language')], max_length=20)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='role',
            new_name='role_en',
        ),
        migrations.AddField(
            model_name='organization',
            name='role_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='external_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='val_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='translation',
            name='val_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='responsibilities_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
